# Generated by Django 2.1.2 on 2020-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200418_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=140),
        ),
    ]
