version: '3'

volumes:
  postgres_data:

services:
  
  python:
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./cse312:/cse312
    ports:
      - 8000:8000
    depends_on:
      - db
    entrypoint: /entrypoint.sh

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    ports:
      - 5432:5432
